
version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data

  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory as needed
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600" # Required for OpenSearch performance analyzer
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    environment:
      COLLECTOR_CONFIG_PATH: /app/config.yaml
      # MINIO_ENDPOINT: http://minio:9000 # Use service name for inter-container communication
    volumes:
      - ./collector/config.yaml:/app/config.yaml
      - ./collector/dev_signer.key:/app/dev_signer.key # Mount dev key
      - ./collector/outbox:/app/outbox # For simulated uploads
    depends_on:
      minio:
        condition: service_healthy
    command: ["./collector"]

  ingest:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    environment:
      OBJECT_STORE_ENDPOINT: minio:9000
      OBJECT_STORE_ACCESS_KEY: minioadmin
      OBJECT_STORE_SECRET_KEY: minioadmin
      OBJECT_STORE_BUCKET: asset-events
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: MyStrongP@ssw0rd!2025#Secure
      PUBLIC_KEYS_PATH: /app/public_keys.json # Placeholder
      GEOIP_DB_PATH: /app/geoip/GeoLite2-City.mmdb # Mount GeoIP DB here
      CVE_RULES_PATH: /app/cve_rules.yaml
    volumes:
      - ./ingest/cve_rules.yaml:/app/cve_rules.yaml
      - ./ingest/archive:/app/archive
      - ./ingest/public_keys.json:/app/public_keys.json # Mount public keys
    depends_on:
      minio:
        condition: service_healthy
      opensearch:
        condition: service_healthy

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: MyStrongP@ssw0rd!2025#Secure
      JWT_SECRET_KEY: super-secret-key
    depends_on:
      opensearch:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8001 # Adjust if API is on different host
    depends_on:
      api:
        condition: service_started # frontend only needs API to be started, not necessarily healthy

  scanner:
    build:
      context: ./scanner
      dockerfile: Dockerfile
    environment:
      SCAN_RATE: 50 # IPs per second (start conservatively)
      SCAN_TIMEOUT: 2.0 # Connection timeout in seconds
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
    depends_on:
      opensearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  minio_data:
  opensearch_data:

